# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used.


PyTorch a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [16]:
import torch

Construct a $5\times 3$ matrix, uninitialized

In [17]:
x = torch.Tensor(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Construct a randomly initialized matrix

In [18]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7780, 0.5218, 0.6342],
        [0.8334, 0.7562, 0.6064],
        [0.9771, 0.0577, 0.5276],
        [0.0151, 0.3596, 0.0781],
        [0.8409, 0.5532, 0.2845]])


Get its size

In [19]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [20]:
x[1:3] = 2
print(x)

tensor([[0.7780, 0.5218, 0.6342],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.0151, 0.3596, 0.0781],
        [0.8409, 0.5532, 0.2845]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [21]:
# 1
x1 = torch.Tensor(2,17)

# 2
x2 = torch.FloatTensor(3,1)

# 3
x3 = torch.LongTensor(5,2,1)
x3.fill_(7)

# 4
x4 = torch.ByteTensor(5)
x4[1:3].fill_(1)

print(f"{x1} \n \n {x2} \n \n {x3} \n  \n {x4}")


tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]) 
 
 tensor([[0.],
        [0.],
        [0.]]) 
 
 tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]]) 
  
 tensor([0, 1, 1, 0, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [22]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.8987, 1.2674, 1.2309],
        [2.1829, 2.4597, 2.5530],
        [2.6899, 2.6788, 2.1602],
        [0.5804, 0.6061, 0.5772],
        [0.8488, 1.0560, 1.1408]])


In [ ]:
# Enhanced device selection: Use CUDA, MPS (Apple Silicon), or CPU
# This is an improved version that works on all platforms

# Check for available devices
if torch.cuda.is_available():
    device = torch.device("cuda")
    device_name = "CUDA (NVIDIA GPU)"
    print(f"🚀 Using {device_name}")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
    device_name = "MPS (Apple Silicon GPU)"
    print(f"🍎 Using {device_name}")
else:
    device = torch.device("cpu")
    device_name = "CPU"
    print(f"💻 Using {device_name}")

# Move tensors to the best available device
x = x.to(device)
y = y.to(device)
z = x + y

print(f"\nTensor locations:")
print(f"x device: {x.device}")
print(f"y device: {y.device}")
print(f"z device: {z.device}")
print(f"\nResult:")
print(z)


### 2.2 Addition: syntax 2

In [23]:
print(torch.add(x, y))

tensor([[0.8987, 1.2674, 1.2309],
        [2.1829, 2.4597, 2.5530],
        [2.6899, 2.6788, 2.1602],
        [0.5804, 0.6061, 0.5772],
        [0.8488, 1.0560, 1.1408]])


### 2.3 Addition: giving an output tensor

In [24]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.8987, 1.2674, 1.2309],
        [2.1829, 2.4597, 2.5530],
        [2.6899, 2.6788, 2.1602],
        [0.5804, 0.6061, 0.5772],
        [0.8488, 1.0560, 1.1408]])


### 2.4 Addition: in-place

adds `x` to `y`

In [25]:
y.add_(x)
print(y)

tensor([[0.8987, 1.2674, 1.2309],
        [2.1829, 2.4597, 2.5530],
        [2.6899, 2.6788, 2.1602],
        [0.5804, 0.6061, 0.5772],
        [0.8488, 1.0560, 1.1408]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [26]:
print(x[:, 1])

tensor([0.5218, 2.0000, 2.0000, 0.3596, 0.5532])


**Read later**: 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [48]:
# 1 using x and y
print(x.mul(y))
print(x)
print()
# 2
print(x.mul_(y))
print(x)
print()
# 3
print(x.div(x))
print()
# 4
x1 = torch.Tensor(2,4)
x2 = torch.Tensor(4,2)
print(f"{x1}, \n \n {x2} \n \n {x1.mm(x2)}")

tensor([[3.3103e-01, 3.4735e+00, 3.3430e+00],
        [1.0310e+03, 2.6798e+03, 3.6092e+03],
        [5.4813e+03, 5.3027e+03, 9.4845e+02],
        [1.9422e-04, 6.5516e-03, 9.6247e-04],
        [2.2659e-01, 8.5559e-01, 8.1622e-01]])
tensor([[3.6835e-01, 2.7407e+00, 2.7158e+00],
        [4.7231e+02, 1.0895e+03, 1.4137e+03],
        [2.0377e+03, 1.9795e+03, 4.3905e+02],
        [3.3465e-04, 1.0809e-02, 1.6674e-03],
        [2.6695e-01, 8.1021e-01, 7.1547e-01]])

tensor([[3.3103e-01, 3.4735e+00, 3.3430e+00],
        [1.0310e+03, 2.6798e+03, 3.6092e+03],
        [5.4813e+03, 5.3027e+03, 9.4845e+02],
        [1.9422e-04, 6.5516e-03, 9.6247e-04],
        [2.2659e-01, 8.5559e-01, 8.1622e-01]])
tensor([[3.3103e-01, 3.4735e+00, 3.3430e+00],
        [1.0310e+03, 2.6798e+03, 3.6092e+03],
        [5.4813e+03, 5.3027e+03, 9.4845e+02],
        [1.9422e-04, 6.5516e-03, 9.6247e-04],
        [2.2659e-01, 8.5559e-01, 8.1622e-01]])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [54]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [55]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [58]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [30]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a NumPy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [65]:
# 1
x1 = torch.ones(5,2)

# 2
x2 = x1.numpy()

# 3
x3 = torch.from_numpy(x2)
print(f"{x1} \n \n {x2} \n \n {x3}")

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]) 
 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 
 
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


# 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [66]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
